### ISSUE TITLE
Nagstamon Stusbar display shows up on wrong screen

### ISSUE THREAD

**Issue by rogermartensson** [HenriWahl/Nagstamon#823] opened 2022-07-07 12:31 UTC
Version: Nagstamon 3.9-20220707
OS: Windows 10 21H2

I have a three-screen setup. My "main screen" is on, as windows calls it, Screen number 2.

When I start Nagstamon with Systray enabled and click the icon the Status Bar shows up at Screen 2.
If I enter Settings and exit out with the OK button then the Status Bar windows starts to display on Screen number 3. If I exit the application and restart it works as intendet.

**Comment by HenriWahl** [comment] 2022-07-07 15:26
Yes - I wish I knew why...

**Comment by HenriWahl** [comment] 2022-07-10 12:24
Please check latest testing releae 3.9-20220710

**Comment by rogermartensson** [comment] 2022-07-11 06:47
I installed it and my first test (open up Settings, press OK) did open up the window on the right screen.
I'll let it sit in the background for a few hours but it seems like you have fixed it.

**Comment by rogermartensson** [comment] 2022-07-11 10:28
The original problem is still fixed but I started to see this. Hope it is OK to use the same issue.
Seem to be a scaling issue?

![bild](https://user-images.githubusercontent.com/12293031/178244721-ff8129d5-00e0-4992-b932-7546bd4efddc.png)

**Comment by HenriWahl** [comment] 2022-07-11 10:52
OK, next challenge...problem is that effect is not clearly reproducible.

**Comment by rogermartensson** [comment] 2022-07-11 10:54
I noticed that because it for a short moment was showing up properly. Not sure if it has anything to do about number of rows.
It's not a major problem for me.

**Comment by rogermartensson** [comment] 2022-07-11 11:53
Some more testing shows me that something happens when we get 10+ rows. If I have 10 rows and click the taskbar icon is is the correct size. The second click on the icon opens up a window taking up almost full screen. I see fulll height but not exactly full width. Is a smaller size centered to the left edge.

**Comment by HenriWahl** [comment] 2022-07-11 15:46
What are your settings for closing the popup window?

**Comment by rogermartensson** [comment] 2022-07-12 06:37
It is set to "Close when hovering out of popup"

Display size: Short, Icon: In Systray, Use offset to correct: 10, Popup when hovering, Close when hovering, highlight new events, show toolstips, Sort: Status, Default sort order: Descending.

**Comment by HenriWahl** [comment] 2022-08-07 12:34
@rogermartensson  Please try latest testing release 3.9-20220807

**Comment by HenriWahl** [comment] 2022-08-15 09:03
@rogermartensson Please try latest testing release 3.9-20220815

**Comment by HenriWahl** [comment] 2022-08-20 06:49
Should be fixed since some versions, closing issue. Otherwise reopen it.

**Closed by HenriWahl** 2022-08-20 06:49 UTC

**Comment by rogermartensson** [comment] 2022-08-25 11:23
You just got me when I was on a vaction but I think you nailed it. I don't have this visual glitch any more.
