### ISSUE TITLE
Nagstamon-3.9-20220626-win64, do not really exit

### ISSUE THREAD

**Issue by BenoitPoulet** [HenriWahl/Nagstamon#819] opened 2022-06-30 13:28 UTC
Hello,

Under Windows 10, as a simple user. The process do not exit when i quit Nagstamon.

The window disappears but the process is still here in my Window's process list, I must kill the process by hand, and not only the Process, but the Process Tree

![image](https://user-images.githubusercontent.com/2464712/176689183-6c662b8e-6cf8-4a03-81f1-2f7aba695f53.png)

**Comment by HenriWahl** [comment] 2022-06-30 15:19
Actually there were changes in thread management - but they should IMPROVE it... :scream:
I will have a look at it.

**Comment by HenriWahl** [comment] 2022-06-30 19:25
Can't reproduce... vanishes from Process Explorer after being finished. Run the .exe from .zip package as main user but not as administrator. How did you start it?

**Comment by BenoitPoulet** [comment] 2022-07-01 09:38
I solved the PB.

I uninstalled Nagstamon, and I deteled the "C:\Program Files\Nagstamon\" Folder, their was plenty of files like DLL.

I purged my ".nagstamon" config dir, and re-installed Nagstamon from the last installer.

The error is gone 👍

**Comment by BenoitPoulet** [comment] 2022-07-04 09:54
The PB come back with the latest build of 04/07

**Comment by HenriWahl** [comment] 2022-07-09 08:35
Still with 20220707?

**Comment by BenoitPoulet** [comment] 2022-07-11 08:42
Unfortunately yes ;(

**Comment by HenriWahl** [comment] 2022-07-11 10:53
And 20220710?

**Comment by BenoitPoulet** [comment] 2022-07-12 07:53
Yes, same.

I did a capture of Processxp with some info, I took it after I exited from Nagstamon by the right-click menu

![image](https://user-images.githubusercontent.com/2464712/178438392-d1f78f86-6eda-440a-affc-c569c6727be1.png)

**Comment by HenriWahl** [comment] 2022-07-15 14:45
As mentioned in #821 - maybe this only happens with activated debug mode?

**Comment by HenriWahl** [comment] 2022-08-14 19:45
Fixed with 3.9-20220814

**Closed** 2022-08-14 19:44 UTC
