### ISSUE TITLE
Nagstamon 2.0.1 stay behind new windows

### ISSUE THREAD

**Issue by loic45** [HenriWahl/Nagstamon#319] opened 2016-09-27 15:33 UTC
The new version 2.0.1 does not remain in the foreground. Is it expected like this ?

**Comment by HenriWahl** [comment] 2016-09-27 16:00
Actually not. Which platform do you refer to? Was it OK in 2.0?

**Comment by loic45** [comment] 2016-09-27 16:11
No. 2.0 is the same that 2.0.1. We had 1.0.1 and the nagstamon always remained in the foreground. We work on seven plateform x64

**Comment by HenriWahl** [comment] 2016-09-27 17:16
What OS? Windows? Linux? MacOS? OS/2?

**Comment by loic45** [comment] 2016-09-28 06:35
We work on windows seven x64.

**Comment by HenriWahl** [comment] 2016-09-28 06:50
Any special applications involved or does this instantly happen?

**Comment by loic45** [comment] 2016-09-29 07:53
No since the installation of the version 2.0, no modification on my desktop.

**Comment by HenriWahl** [comment] 2016-09-29 09:46
Does Nagstamon get back to front sometimes or does it stay in the background? Is it in the back all the time or does it happen sometimes?

**Comment by HenriWahl** [comment] 2016-10-06 16:29
What else software is running typically all the time on your desktop?

**Comment by bastien30** [comment] 2016-10-07 10:02
Hi,

Same problem on my workstation : Windows 10 x64.

Nagstamon doesn't get back to front, even when clicking on "Save position", the only solution is to restart it.
When the problem happens, if I reduce all the desktop by clicking on the right down corner (at right of the systray), Nagstamon is reduced too.

Typically programs that run all the time on my desktop :
- Kitty (fork of putty)
- Pidgin
- Keepass
- Owncloud desktop client
- Rainmeter
- OCS Inventory Agent
- Kaspersky Endpoint Security 10

Thanks.

**Comment by HenriWahl** [comment] 2016-10-07 10:16
Getting it on front at all is a major desaster on Windows - I was only able to kind of solve with a dirtier than dirty workaround. Quite possibly this interferes with some other alway-on-top or always-present tool. Can you - just for testing - try in a session without any other startup tool?

**Comment by bastien30** [comment] 2016-10-07 10:32
Thanks for the quick reply.

I suspect this has maybe to do with Rainmeter because it is always on top of the desktop.
Furthermore, my colleague doesn't have the problem and he hasn't this program (he have all of the others).

I will test without it and let you know.

**Comment by HenriWahl** [comment] 2016-10-07 10:50
If you are able to change startup order or to delay the start of Rainmeter (however this should be accomplished) you might "fix" this.

**Comment by bastien30** [comment] 2016-10-12 15:06
After testing for couple of days, the problem is not caused by Rainmeter.
It is caused by my tilling window manager : Mosaico (http://www.soulidstudio.com/).
Every time I restore a snapshot, Nagstamon doesn't stay on top, until I restart it.

**Comment by HenriWahl** [comment] 2016-10-12 17:09
This sounds possible. I have no experience with Mosaico but if it controls window behavior somehow this might be the case it disturbs Nagstamon's own manipulations. Maybe you can configure special Mosaico-Nagstamamon-settings?

**Comment by bastien30** [comment] 2016-10-14 13:08
I've searched but there is not special setting, at least in the free edition.
Anyway, I've uninstalled Mosaico, Nagstamon is more important for me.

**Comment by HenriWahl** [comment] 2016-10-15 14:44
And not using Mosaico helps?

**Comment by bastien30** [comment] 2016-10-17 09:09
Without Mosaico, Nagstamon stays always on top.

**Comment by HenriWahl** [comment] 2016-10-17 12:58
So I assume I might close this issue as there is nothing I can do,

**Closed by HenriWahl** 2016-10-17 12:58 UTC
