### ISSUE TITLE
Filters for Check_MK Multisite

### ISSUE THREAD

**Issue by ghost** [HenriWahl/Nagstamon#132] opened 2015-02-25 08:59 UTC
The Filters options Filter out "Acknowledged hosts & services", "Hosts & services with disabled notifications", "Hosts & services with disabled checks" and "Hosts & services down for maintenance" are not working for Server type "Check_MK Multisite" because on every request the following Strings are appended:
url_params += '&is_host_acknowledged=-1&is_service_acknowledged=-1'
url_params += '&is_host_notifications_enabled=-1&is_service_notifications_enabled=-1'
url_params += '&is_host_active_checks_enabled=-1&is_service_active_checks_enabled=-1'
url_params += '&host_scheduled_downtime_depth=-1&is_in_downtime=-1'
instead of building them dynamically.

**Comment by HenriWahl** [comment] 2015-02-25 10:03
Must be a misunderstanding, because filtering is not done by URLS but after retrieval inside Nagstamon. There are some filtering issues, but these are not related to URLs. 
After Qt port there will be time to fix these.

**Comment by tyhawk** [comment] 2016-02-18 14:13
I can confirm that this issue still persists in version 2.0-alpha-20160206.

**Comment by ciberconceito** [comment] 2016-02-25 14:10
I have the same problem and it was already present in version 1.0.1
I went for 2.0 alpha to see if it was solved there.

**Comment by HenriWahl** [comment] 2016-02-25 15:10
Most changed until now happened in the GUI port to Qt5. If finished the server bugs will be investigated.

**Closed** 2016-04-25 06:24 UTC
