### ISSUE TITLE
No refreshing when disconnected from Monitoring PC

### ISSUE THREAD

**Issue by eventmarkus** [HenriWahl/Nagstamon#804] opened 2022-02-22 14:27 UTC
We use nagstamon 3.8.0 on our TV in the office. Installed is a Windows 10 20H2. Unfortunately, the refresh stops as soon as you close the SCCM remote control window. See screenshot below. When you connect, the message "Refreshing..." appears immediately in the upper right corner and the data is up to date again. I don't want to have always an SCCM remote control window open to the office PC, so that the data is refreshed every 60 seconds. How can we fix this? 

![image](https://user-images.githubusercontent.com/25842969/155152173-1d9c1abe-80a0-401b-a12e-c0733bdfffc7.png)

**Comment by eventmarkus** [comment] 2022-02-22 17:08
> Strange... why is the SCCM remote console involed?

So that you can operate the PC remotely. Change radio station, print label, update monitoring, etc.

**Comment by HenriWahl** [comment] 2022-02-22 17:42
Well... if this is a valid workaround.
Honestly I do not see why there is such a dependency between whatever lifesign of a user and Nagstamon doing its refreshes. Seems hard to debug. Maybe you could run it from source and see if a terminal output brings some light to it?

**Comment by HenriWahl** [comment] 2022-04-19 21:48
Sorry, looks like a very edgy case I cannot reproduce and @eventmarkus has a workaround so I close this issue.

**Closed by HenriWahl** 2022-04-19 21:48 UTC
