### ISSUE TITLE
Centreon Bad Session ID

### ISSUE THREAD

**Issue by sdoern** [HenriWahl/Nagstamon#151] opened 2015-07-24 10:51 UTC
Hi,

we want to use Nagstamon for combined with Centreon. After 10 -20 min the tool show the status OK because they cant fetch the URL. The session ID that is used in the url fetch link is expired and the reply code is Bad Session ID. Does anyone know a solution to this problem?

**Comment by HenriWahl** [comment] 2015-07-27 12:26
Which version of Nagstamon shows this behaviour?

**Comment by sdoern** [comment] 2015-07-27 13:15
Version 1.0.1 for Windows. Installed via Nagstamon_1.0.1_setup.exe.

**Comment by HenriWahl** [comment] 2015-07-27 13:26
This case should be catched and a new session created. Maybe a regression bug... did it work with a prior version?

**Comment by sdoern** [comment] 2015-07-28 12:00
Now i have test the versions 0.9.8 to 1.0.1. The version 0.9.9 to 1.0.1 also run in state Ok after 20 min. 

The version 0.9.8 looks better. In the log i see the bad session ID message and the tool goes in OK state. After 20sec nagstamon make a relogin and the state is after the refresh time ok. 

In the version 0.9.8 we find out that the filter "Host & Service with disable checks" filter also passive checks out!

**Comment by HenriWahl** [comment] 2015-07-29 10:25
So it looks like a reintroduced bug. Thanks for testing.

**Comment by sdoern** [comment] 2015-07-30 06:39
It is planned to develop an update?

**Comment by HenriWahl** [comment] 2015-07-30 07:32
I will check this issue when I am done with this apparently never finished Qt5 port...

**Comment by HenriWahl** [comment] 2016-05-19 11:19
Please check the latest 20160519 binaires from https://nagstamon.ifw-dresden.de/nagstamon-20/

**Comment by HenriWahl** [comment] 2016-05-29 08:45
Any progress?

**Comment by HenriWahl** [comment] 2016-05-31 15:11
Hook() code was brought back by @benoiteolas so I assume this being fixed now.

**Closed by HenriWahl** 2016-05-31 15:11 UTC
