### ISSUE TITLE
Nagstamon  3.8 /3.9 and  Centreon 22.04.0

### ISSUE THREAD

**Issue by RAICO-IT** [HenriWahl/Nagstamon#815] opened 2022-06-23 10:07 UTC
Hello,

We have a problem in the interaction of Nagstamon 3.8 or 3.9 and the new Centreon version 22.04.0. Nagstamom only shows the message "Empty host XML result" We have already tried everything possible to solve this problem, but we are not getting any further. 
Jumping from Nagstamon to Monitor, Host etc. works without errors. 
Does anyone have an idea how we can solve this problem or is the Centreon version too new and everything is different there?
We would be very grateful for any tips!

**Comment by HenriWahl** [comment] 2022-06-23 17:40
Which version of Nagstamon 3.9 do you use?

**Comment by RAICO-IT** [comment] 2022-06-24 05:52
We use the version 3.9-20220619.
But even with the officially released v. 3.8 we get the same message.

**Comment by jcdubassin** [comment] 2022-06-24 13:41
same problem for me since 22.04..... "Empty host XML result"

**Comment by BenoitPoulet** [comment] 2022-06-24 13:46
Hello,

The support for Centreon 22.04 and the API V2 has been added to Nagstamon.

**BUT** this is no access to it as the integration is missing : no config screen, no possibility to switch on the right class

as discussed here : https://github.com/HenriWahl/Nagstamon/issues/812

**Comment by HenriWahl** [comment] 2022-06-26 13:16
I added a new branch to integrate the new Centreon API. Addititonally I created a switch at https://github.com/HenriWahl/Nagstamon/blob/integrate_centreon_api/Nagstamon/Servers/Centreon/__init__.py.
@BenoitPoulet  this does not work yet for me but maybe this is a prototype how it could work? Can you please have a more Centreonic look at it?

**Comment by guinfox** [comment] 2022-06-27 14:46
Here we have the same problem.

**Comment by guinfox** [comment] 2022-06-27 14:46
centreon 22.04 and nagstamon 3.9 :(

**Comment by HenriWahl** [comment] 2022-06-29 04:51
Please check the latest testing release from https://github.com/HenriWahl/Nagstamon/releases/tag/latest which tries to access this issue.

**Comment by RAICO-IT** [comment] 2022-06-29 06:38
Hello to all who have worked on this problem. 
With the new version everything works again.
It's nice to see that sometimes things work in IT! Many thanks to everyone who was involved in solving the problem!

**Comment by jcdubassin** [comment] 2022-06-29 08:24
Thanks !!!

**Comment by MrManjah** [comment] 2022-06-29 10:39
Hi everyone !
Doesn't work for me with :(
Centreon 22.04.0 and nagstamon 3.9-20220626

**Comment by jcdubassin** [comment] 2022-06-29 11:31
> Hi everyone ! Doesn't work for me with :( Centreon 22.04.0 and nagstamon 3.9-20220626 Installer : [Nagstamon-3.9-20220626-win64_setup.exe](https://github.com/HenriWahl/Nagstamon/releases/download/latest/Nagstamon-3.9-20220626-win64_setup.exe)

Same version for me , works fine ( centreon 22.04 )

**Comment by MrManjah** [comment] 2022-06-29 11:51
Here the trace logs in debug mode : 

DEBUG: 2022-06-29 13:43:49.020790 Centreon Checking session status
DEBUG: 2022-06-29 13:43:49.020790 Centreon URLs defined for Centreon 19.04
DEBUG: 2022-06-29 13:43:49.020790 Centreon FetchURL: https://ServerName/centreon/api/internal.php?object=centreon_keepalive&action=keepAlive CGI Data: None
DEBUG: 2022-06-29 13:43:49.128497 Centreon Session status : "Unauthorized", http code : 401
DEBUG: 2022-06-29 13:43:49.128497 Centreon FetchURL: https://ServerName/centreon/index.php CGI Data: None
ERROR: 2022-06-29 13:43:49.200052 Centreon Traceback (most recent call last):
  File "Nagstamon\Servers\Centreon\CentreonLegacy.py", line 263, in _get_sid
AttributeError: 'NoneType' object has no attribute 'find'
DEBUG: 2022-06-29 13:43:49.200052 Centreon Session renewed
DEBUG: 2022-06-29 13:43:49.200052 Centreon FetchURL: https://ServerName/centreon/include/monitoring/status/Hosts/xml/hostXML.php?num=0&limit=9999&o=hpb&p=20202&criticality=0&statusHost=hpb&sSetOrderInMemory=1 CGI Data: None
DEBUG: 2022-06-29 13:43:49.266987 Centreon Empty host XML result

**Comment by MrManjah** [comment] 2022-06-29 12:07
Thks @jcdubassin . Do you use a SSL certificate on Centreon web server ?

**Comment by BenoitPoulet** [comment] 2022-06-29 16:08
@MrManjah Can you give more information ? 
Centreon version ?
Error you have and if you can, enable the debug and post the log (without private information)

I run this version on Centreon 22.04 with valid SSL certificate, and on another one in HTTP.

Please note that using «autologin» is not supported on 22.04, you must use login/password.
Be careful to try with the latest version posted 3 hours ago https://github.com/HenriWahl/Nagstamon/releases/tag/latest

**Comment by MrManjah** [comment] 2022-06-30 07:35
Hi @BenoitPoulet ,
Here the informations : 
Centreon version 22.04.0 Centreon 22.04.0 and nagstamon 3.9-20220626 with the latest binary (18h ago)

Debug logs : 
ERROR: 2022-06-30 09:27:17.819630 Centreon Traceback (most recent call last):
  File "Nagstamon\Servers\Centreon\CentreonLegacy.py", line 263, in _get_sid
AttributeError: 'NoneType' object has no attribute 'find'
DEBUG: 2022-06-30 09:27:17.819630 Centreon Session renewed
DEBUG: 2022-06-30 09:27:17.819630 Centreon FetchURL: https://server/centreon/include/monitoring/status/Hosts/xml/hostXML.php?num=0&limit=9999&o=hpb&p=20202&criticality=0&statusHost=hpb&sSetOrderInMemory=1 CGI Data: None
DEBUG: 2022-06-30 09:27:17.885695 Centreon Empty host XML result
DEBUG: 2022-06-30 09:27:47.939743 Centreon Checking session status
DEBUG: 2022-06-30 09:27:47.939743 Centreon URLs defined for Centreon 19.04
DEBUG: 2022-06-30 09:27:47.939743 Centreon FetchURL: https://server/centreon/api/internal.php?object=centreon_keepalive&action=keepAlive CGI Data: None
DEBUG: 2022-06-30 09:27:48.229024 Centreon Session status : "Unauthorized", http code : 401
DEBUG: 2022-06-30 09:27:48.229024 Centreon FetchURL: https://server/centreon/index.php CGI Data: None
ERROR: 2022-06-30 09:27:48.304101 Centreon Traceback (most recent call last):
  File "Nagstamon\Servers\Centreon\CentreonLegacy.py", line 263, in _get_sid
AttributeError: 'NoneType' object has no attribute 'find'

**Comment by BenoitPoulet** [comment] 2022-06-30 07:48
I can see that the auto-detection of the Centreon's version failed.

The auto-detection relies on this page , car you to try to access to it without being logged into Centreon ?

https://server/centreon/api/latest/platform/versions

**Comment by MrManjah** [comment] 2022-06-30 10:08
It work in private browsing with result like this :
{"web":{"version":"22.04.0","major":"22","minor":"04","fix":"0"}.....

**Comment by BenoitPoulet** [comment] 2022-06-30 13:11
The log you sent is not complete, the beginning is missing.

it must look like this :

```
DEBUG: 2022-06-30 14:55:56.560070 preprod FetchURL: https://centreon-preprod/centreon/api/latest/platform/versions CGI Data: None
DEBUG: 2022-06-30 14:55:56.827359 [preprod] Status code 200
DEBUG: 2022-06-30 14:55:56.828356 [preprod] Loading class API, Centreon version : 22.4
DEBUG: 2022-06-30 14:55:56.828356 preprod Created server.
DEBUG: 2022-06-30 14:55:56.836364 preprod FetchURL: https://centreon-preprod/centreon/api/latest/platform/versions CGI Data: None
DEBUG: 2022-06-30 14:55:57.056834 [preprod] Centreon code version selected : >= 21
DEBUG: 2022-06-30 14:55:57.056834 [preprod] URLs defined for Centreon vers. : 22
DEBUG: 2022-06-30 14:55:57.060775 preprod FetchURL: https://centreon-preprod/centreon/api/latest/login CGI Data: {"security": {"credentials": {"login": "mylogin", "password": "xxxxxxxxxxxxxxx"}}}
DEBUG: 2022-06-30 14:55:57.785054 preprod Fetched JSON: {'contact': {'alias': 'mylogin',
             'email': 'mylogin',
             'id': 96,
             'is_admin': False,
             'name': 'my name'},
 'security': {'token': 'pSZ1hDy64+so83axTvKsebpVKS1jUBA0Ks4Bn7XQYLVGhdxuLAU2HfiOUYeg8QIM'}}
DEBUG: 2022-06-30 14:55:57.785054 [preprod] API login : mylogin / xxxxxxxxxxxxxxx > Token : pSZ1hDy64+so83axTvKsebpVKS1jUBA0Ks4Bn7XQYLVGhdxuLAU2HfiOUYeg8QIM > User ID : 96
DEBUG: 2022-06-30 14:55:57.785054 [preprod] Checking session status
DEBUG: 2022-06-30 14:55:57.785054 [preprod] Check-session, the token will be deleted if it has not been used for more than one hour. Current Token = pSZ1hDy64+so83axTvKsebpVKS1jUBA0Ks4Bn7XQYLVGhdxuLAU2HfiOUYeg8QIM
DEBUG: 2022-06-30 14:55:57.786018 preprod FetchURL: https://centreon-preprod/centreon/api/latest/monitoring/resources?limit=0 CGI Data: None
DEBUG: 2022-06-30 14:55:58.121103 preprod Check-session, Fetched JSON: {'meta': {'limit': 0, 'page': 1, 'search': {}, 'sort_by': {}, 'total': 31},
 'result': []}
DEBUG: 2022-06-30 14:55:58.121103 preprod Check-session, Error : , Status code : 200
DEBUG: 2022-06-30 14:55:58.121103 preprod FetchURL: https://centreon-preprod/centreon/api/latest/monitoring/resources?types=["host"]&statuses=["WARNING","DOWN","CRITICAL","UNKNOWN"]&limit=9999 CGI Data: None
DEBUG: 2022-06-30 14:55:58.387568 [preprod] Host indexed : dirv-monitoring-centreon-02
DEBUG: 2022-06-30 14:55:58.387568 preprod FetchURL: https://centreon-preprod/centreon/api/latest/monitoring/resources?types=["metaservice","service"]&statuses=["WARNING","DOWN","CRITICAL","UNKNOWN"]&limit=9999 CGI Data: None

```

**Comment by BenoitPoulet** [comment] 2022-07-04 09:49
Please be careful, the latest release publish the 04/07 from commit #376eee8,  does not contain the Centreon 22.04 support anymore.
@HenriWahl is this intended ?

**Comment by HenriWahl** [comment] 2022-07-04 10:17
No, this is not intended. I am checking what went wrong.

**Comment by HenriWahl** [comment] 2022-07-04 10:22
Building 3.9-20220704 at the moment, shall be available in some minutes and contains the merge again.

**Comment by ASLLR** [comment] 2022-08-08 07:06
Hello, 

I've the same problem : 
`https://$SERVER/include/monitoring/status/Hosts/xml/hostXML.php?num=0&limit=9999&o=hpb&p=20202&criticality=0&statusHost=hpb&sSetOrderInMemory=1 CGI Data: None`

I use Centreon 22.04.1 with Nagstamon 3.9-20220807. 

Thank you for your help

**Comment by HenriWahl** [comment] 2022-08-08 07:55
@ASLLR as this thread grew a lot - which problem exactly?

**Comment by ASLLR** [comment] 2022-08-08 08:01
Hi @HenriWahl thank for your answer, i speak about the compatibility with Centreon 22.04. I've update my server and after nagstamon stop working with "Monitor URL Invalid". In debug mode i can the the line : 
`https://$SERVER/include/monitoring/status/Hosts/xml/hostXML.php?num=0&limit=9999&o=hpb&p=20202&criticality=0&statusHost=hpb&sSetOrderInMemory=1 CGI Data: None` 
I think is linked with the forst message of this issue.

Best Regards,

**Comment by brice-automatizit** [comment] 2022-08-08 08:11
Hi guys,

I got the following despite I had uncheck the box ignore ssl certificate and/or setting my server's certificate and/or the complete chain: 

> DEBUG: 2022-08-08 09:51:52.426089 Monitor server FetchURL: https://myfqdn/centreon/api/latest/platform/versions CGI Data: None
> ERROR: 2022-08-08 09:51:52.552304 Monitor server Traceback (most recent call last):
>   File "urllib3\connectionpool.py", line 703, in urlopen
>   File "urllib3\connectionpool.py", line 386, in _make_request
>   File "urllib3\connectionpool.py", line 1042, in _validate_conn
>   File "urllib3\connection.py", line 414, in connect
>   File "urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
> ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:997)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "requests\adapters.py", line 489, in send
>   File "urllib3\connectionpool.py", line 787, in urlopen
>   File "urllib3\util\retry.py", line 592, in increment
> urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='myfqdn', port=443): Max retries exceeded with url: /centreon/api/latest/platform/versions (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:997)')))


If that can help, I remember that I had to add some 
"self.session.verify = False" in multiple place (Generic.py & Centreon.py) to implement quickly the fix from Benoit but I don't remember exactly the modification I made. It also fixed the issue with the verification of update as we have SSL decryption in our corporate network.

**Comment by HenriWahl** [comment] 2022-08-08 19:33
@ASLLR Do you use autologin which should NOT work as described in https://github.com/HenriWahl/Nagstamon/issues/815#issuecomment-1170180568 ?

**Comment by HenriWahl** [comment] 2022-08-08 19:40
@brice-automatizit did you **check** or **uncheck** the ignore SSL setting?

**Comment by ASLLR** [comment] 2022-08-09 06:08
> @ASLLR Do you use autologin which should NOT work as described in [#815 (comment)](https://github.com/HenriWahl/Nagstamon/issues/815#issuecomment-1170180568) ?

Hi @HenriWahl no i'm not using autologin. 

Best regards

**Comment by brice-automatizit** [comment] 2022-08-09 07:16
> @brice-automatizit did you **check** or **uncheck** the ignore SSL setting?

Indeed, I ***check**ed the box to ignore the TLS/SSL certificate

**Comment by JGomsss** [comment] 2022-08-12 19:39
> 

Hello,
I've the same problem with Nagstamon 3.9-20220808.

**Comment by HenriWahl** [comment] 2022-08-14 16:03
@ASLLR  the URL you posted looks like an old Centreon URL?

**Comment by HenriWahl** [comment] 2022-08-14 16:49
Please check latest builds 3.9-20220814 from https://github.com/HenriWahl/Nagstamon/releases/tag/latest where the SSL verify problem is apparently fixed.

For **new issues** please open a new issue because this thread becomes somewhat confusing - thanks!  :sunglasses: l

**Comment by JGomsss** [comment] 2022-08-16 06:31
I've the same problem with Nagstamon 3.9-20220814 : Empty host result

**Comment by ASLLR** [comment] 2022-08-16 06:40
> @ASLLR the URL you posted looks like an old Centreon URL?

Hi @HenriWahl yes i use https://centreon.domain.com/ it's not that now with the new version of centreon ? 

I've installed Nagstamon 3.9-20220815 and i've the "monitor invalid URL" error message. 

Thank you in advance. If you want, i can open a new issue. 

Best regards

**Comment by HenriWahl** [comment] 2022-08-16 07:09
> I've the same problem with Nagstamon 3.9-20220815 : Empty host result

@JGomsss did anything work before?

**Comment by HenriWahl** [comment] 2022-08-16 07:11
> > @ASLLR the URL you posted looks like an old Centreon URL?
> 
> Hi @HenriWahl yes i use https://centreon.domain.com/ it's not that now with the new version of centreon ? 

@BenoitPoulet @ASLLR I would say ther is some sub-part line /centreon necessary?

**Comment by ASLLR** [comment] 2022-08-16 07:15
> > > @ASLLR the URL you posted looks like an old Centreon URL?
> > 
> > 
> > Hi @HenriWahl yes i use https://centreon.domain.com/ it's not that now with the new version of centreon ?
> 
> @BenoitPoulet @ASLLR I would say ther is some sub-part line /centreon necessary?

Yes that is, i forgot that because i've an automatic redirection. I've the same message of other "empty host XML result". 

Thank you in advance.

**Comment by JGomsss** [comment] 2022-08-16 07:29
> > I've the same problem with Nagstamon 3.9-20220815 : Empty host result
> 
> @JGomsss did anything work before?

Before Centreon 22.04.0, everything was working fine

**Comment by HenriWahl** [comment] 2022-08-16 07:37
@ASLLR @JGomsss please enable debugging and show us its output. Thanks!

**Comment by ASLLR** [comment] 2022-08-16 08:15
@HenriWahl 

[nagstamon_debug.txt](https://github.com/HenriWahl/Nagstamon/files/9348960/nagstamon_debug.txt)
This is the debug file anonymized on URL. 

Thank you in advance

**Comment by JGomsss** [comment] 2022-08-16 08:40
@HenriWahl 

Debug file below and anonymized too.
[nagstamon-debug .log](https://github.com/HenriWahl/Nagstamon/files/9349126/nagstamon-debug.log)

Thanks in advance

**Comment by HenriWahl** [comment] 2022-08-16 14:42
@JGomsss looks like a custom certificate is not ignored and so right in the beginning the version detection fails. So it falls back to old legacy code which does not apply to your current server. Do you right now use a custom CA and ignore it?

**Comment by HenriWahl** [comment] 2022-08-16 14:45
@ASLLR the debug log is pretty short, I only see you are unauthorized and also the older Centreon version was assumed.

**Comment by ASLLR** [comment] 2022-08-17 07:08
> @ASLLR the debug log is pretty short, I only see you are unauthorized and also the older Centreon version was assumed.

Hi @HenriWahl  thank you for your answer. You know why this message appear : `URLs defined for Centreon 19.04` whereas i've a centreon 22.04 ? 
i don't know why i've a 401 error... 

Thank you in advance.

**Comment by HenriWahl** [comment] 2022-08-17 12:38
@ASLLR This must be investigated.

The 401 error indicates some auhorization problem?

**Comment by HenriWahl** [comment] 2022-08-17 12:52
> @HenriWahl : We have a custom certificate but Ignore SSL/TLS Certificat box is checked.
> If ignore certificate is not checked, we have this error `TypeError:'>=' not supported between instances of 'NoneType' and 'float`

@JGomsss can you send me a log where this error is included?

**Comment by HenriWahl** [comment] 2022-08-17 12:53
@ASLLR maybe you can send us a longer log?

**Comment by ASLLR** [comment] 2022-08-17 13:57
> @ASLLR maybe you can send us a longer log?

@HenriWahl I've install the 3.9-20220817 version on a fresh computer and now i've certificate error in the debug, i use the option of custom CA but the result is the same "Empty host XML result".
[nagstamon_debug.txt](https://github.com/HenriWahl/Nagstamon/files/9363271/nagstamon_debug.txt)

Thank in advance.

**Comment by JGomsss** [comment] 2022-08-17 15:52
> > @HenriWahl : We have a custom certificate but Ignore SSL/TLS Certificat box is checked.
> > If ignore certificate is not checked, we have this error `TypeError:'>=' not supported between instances of 'NoneType' and 'float`
> 
> @JGomsss can you send me a log where this error is included?

@HenriWahl 

Debug file below and anonymized too. Tested with 3.9-20220817 version.
For information, we use wildcard certificate
[nagstamon-debugSSL.log](https://github.com/HenriWahl/Nagstamon/files/9364350/nagstamon-debugSSL.log)

**Comment by HenriWahl** [comment] 2022-08-17 23:34
@ASLLR @JGomsss I could reproduce this misbehaviour and found a fix. Please check the fresh 3.9-20220818 release.

**Comment by JGomsss** [comment] 2022-08-18 06:51
@HenriWahl 
With ingore SSL, I have this error `json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char(0)`
[nagstamon3.9-20220818_IgnoreSSL.log](https://github.com/HenriWahl/Nagstamon/files/9368281/nagstamon3.9-20220818_IgnoreSSL.log)
And with SSL, I have this error `TypeError:'>=' not supported between instances of 'NoneType' and 'float`
[nagstamon3.9-20220818_WithSSL.log](https://github.com/HenriWahl/Nagstamon/files/9368285/nagstamon3.9-20220818_WithSSL.log)

**Comment by ASLLR** [comment] 2022-08-18 09:05
> @ASLLR @JGomsss I could reproduce this misbehaviour and found a fix. Please check the fresh 3.9-20220818 release.

Hi @HenriWahl  if i ignore the ssl certificate that work for me the host appear !! 

you rock !! 

Best regards

**Comment by ASLLR** [comment] 2022-08-18 09:46
> 



> @HenriWahl With ingore SSL, I have this error `json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char(0)` [nagstamon3.9-20220818_IgnoreSSL.log](https://github.com/HenriWahl/Nagstamon/files/9368281/nagstamon3.9-20220818_IgnoreSSL.log) And with SSL, I have this error `TypeError:'>=' not supported between instances of 'NoneType' and 'float` [nagstamon3.9-20220818_WithSSL.log](https://github.com/HenriWahl/Nagstamon/files/9368285/nagstamon3.9-20220818_WithSSL.log)

After a moment i've this error to : `json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char(0)`

**Comment by MrManjah** [comment] 2022-08-18 16:13
Hi every body ! @HenriWahl it work for me since last release. Thanks 
@ASLLR you must enable Reach API Realtime on centreon user account configuration
![image](https://user-images.githubusercontent.com/31627375/185443677-e226fbf8-0f81-4b37-b777-3ef65b4cf67d.png)

**Comment by JGomsss** [comment] 2022-08-19 05:46
@HenriWahl  , @MrManjah ,
It work for me since last release with `Reach API Realtime` enable. 
Thanks

**Comment by HenriWahl** [comment] 2022-08-19 05:54
@MrManjah @JGomsss do you know what this setting means?

**Comment by MrManjah** [comment] 2022-08-19 08:05
@HenriWahl it allow user to perform Centreon API calls.
[https://docs.centreon.com/fr/docs/api/rest-api-v1/#permissions](https://docs.centreon.com/fr/docs/api/rest-api-v1/#permissions)

**Comment by HenriWahl** [comment] 2022-08-20 06:53
@ASLLR does it work for you with the recommendation of @MrManjah ?

**Comment by maxdevaine** [comment] 2022-10-05 08:11
Current version of Nagstamon (3.9-20221003)
https://github.com/HenriWahl/Nagstamon/releases/download/latest/Nagstamon-3.9-20221003-win64_setup.exe
https://github.com/HenriWahl/Nagstamon/releases/download/latest/Nagstamon-3.9-20221003-win32_setup.exe
is ok (login user+pw) with latest version of Centreon (ver 22.04.6)
Login via key is not working due to #812.

Max

**Comment by BenoitPoulet** [comment] 2022-12-12 09:21
@HenriWahl 
I think this issue can be closed

**Comment by ASLLR** [comment] 2022-12-12 13:12
Hi @BenoitPoulet and @HenriWahl, yes you could close this one. 

Thank you.

**Closed** 2022-12-12 19:29 UTC
