### ISSUE TITLE
Converting Problem when using IcingaDB-Web

### ISSUE THREAD

**Issue by robertkrenn** [HenriWahl/Nagstamon#997] opened 2023-12-14 15:58 UTC
When swtitching the nagstamon Setting from Icingaweb2 to IcingaDB-Web, nagstamon only shows Error. The Debug Log shows further:

DEBUG: 2023-12-14 16:06:29.148170 Icingadb FetchURL: https://icinga2.augsburg.de/icingaweb2/icingadb/hosts?host.state.is_problem=y&host.state.state_type=hard&columns=host.state.last_update&format=json CGI Data: None
ERROR: 2023-12-14 16:06:29.313691 Icingadb Traceback (most recent call last):
  File "Nagstamon\Servers\IcingaDBWeb.py", line 214, in _get_status
**ValueError: could not convert string to float: '2023-12-14T10:47:42.512+00:00'**

Nagstamon 3.12 is installed.

**Comment by sebek72** [comment] 2023-12-15 07:43
You need a newer version of nagstamon...take the latest build.

**Comment by HenriWahl** [comment] 2023-12-18 06:00
@robertkrenn which version of Nagstamon do you use? The testing releases contain IncingaDB-Web compatibility.

**Comment by robertkrenn** [comment] 2023-12-18 07:28
@HenriWahl We use the last stable Version 3.12.0, I'll try the latest build.

**Comment by robertkrenn** [comment] 2023-12-18 16:13
In Version 3.13- 20231208 I get the following error:


DEBUG: 2023-12-18 17:09:46.543998 Icingadb FetchURL: https://icinga2.augsburg.de/icingaweb2/icingadb/hosts?host.state.is_problem=y&host.state.state_type=hard&columns=host.state.last_update&format=json CGI Data: None
DEBUG: 2023-12-18 17:09:46.626802 Icingadb FetchURL: https://icinga2.augsburg.de/icingaweb2/icingadb/hosts?host.state.is_problem=y&host.state.state_type=soft&columns=host.state.last_update&format=json CGI Data: None
DEBUG: 2023-12-18 17:09:46.693537 Icingadb FetchURL: https://icinga2.augsburg.de/icingaweb2/icingadb/services?service.state.is_problem=y&service.state.state_type=hard&columns=service.state.last_update,service.state.is_reachable&format=json CGI Data: None
ERROR: 2023-12-18 17:09:47.063121 Icingadb Traceback (most recent call last):
  File "Nagstamon\Servers\IcingaDBWeb.py", line 320, in _get_status
AttributeError: 'NoneType' object has no attribute 'replace'

**Comment by Tontonitch** [comment] 2023-12-19 17:11
To better evaluate your situation, could you provide icinga related software versions that you are using:
`apt list icingaweb2 icingadb icingadb-web icinga2 icingaweb2-module-monitoring`
or
`yum list installed icingaweb2 icingadb icingadb-web icinga2 icingaweb2-module-monitoring`

That could help evaluating if the issue comes from a recent version of one of these components.

**Comment by Tontonitch** [comment] 2023-12-19 17:14
Seems a duplicate of #996

**Comment by robertkrenn** [comment] 2023-12-20 06:04
![grafik](https://github.com/HenriWahl/Nagstamon/assets/33095071/7c073dbe-75bd-4898-8da6-0d1dcc4a7017)

**Closed** 2024-01-08 21:09 UTC
