### ISSUE TITLE
Zabbix connection is not restored when host not found on startup.

### ISSUE THREAD

**Issue by xgrzechu** [HenriWahl/Nagstamon#650] opened 2020-06-18 09:53 UTC
I'm using Nagstamon with nagios and zabbix over VPN, when vpn is not connected both hosts (zabbix and nagios) can't be resolved. After connecting vpn Nagios works, but zabbix shows connection error and I have to restart app to make it work. 

It would be nice if once every few minutes new attempt is made to resolve host and reconnect for zabbix host. 

Thanks!

my version 3.4.1 for windows

**Comment by hyperman1** [comment] 2020-07-13 06:25
I can confirm this issue on both nagstamon 3.4.1 and  3.2.1.    Clicking on recheck all or refresh does not restore the nectwork connection.  Only completely closing nagstamon fixes it.

If the VPN disappears and later reappears, the connection is restored.  The problem seems to be the default network that changes.

**Comment by hyperman1** [comment] 2020-08-24 09:54
FIX AVAILABLE.

I've looked in the source code.  _login resets everythhing if sel.zapi is None.  Hence, you can set it back to None if you see 
 except ZabbixError or ZabbixAPIException 's that return, and the next poll will repair it.

def _get_status(self):
        self._login()
        try: 
                  [More code]
       except ZabbixError:
            self.zapi = None  #I added this   <-----------------------------------
            self.isChecking = False
            result, error = self.Error(sys.exc_info())
            return Result(result=result, error=error)
       [More exception handlers treated like this]

I do notice:  
  _set_acknowledge does not handle this error 
 _set_downtime does not handle this error and does not call self._login()
I assume these are bugs, but harmless as long as the previous _get_status was succesfull

**Comment by HenriWahl** [comment] 2021-04-15 10:35
Sorry for the really late reply... can you please check if this still is valid for latest 3.6.0 and in the best case create a pull request to get in into easily?

**Comment by hyperman1** [comment] 2021-04-19 06:34
Sorry for my late reply too, I was on holiday.

Our corporation does not allow me to create PRs.  I'll do it on my personal laptop in a few day when I am back home.

***@***.***D734F6.C948F580]
Hans Yperman | CM Oostende
Expert, Dienst informatica & Competence Center Ontwikkeling
Christelijke mutualiteit Oostende - Veurne - Diksmuide(112)
Ieperstraat 12 - 8400 OOSTENDE
059/55.26.35
www.cm.be<http://www.cm.be> I facebook<https://www.facebook.com/CMziekenfonds> I twitter<https://twitter.com/CMziekenfonds> I linkedin<http://www.linkedin.com/company/christelijke-mutualiteit-cm-mutualit-chr-tienne-mc-> I e-mail disclaimer<http://www.cm.be/disclaimer/e-mail-disclaimer.jsp>

Van: Henri Wahl ***@***.***>
Verzonden: donderdag 15 april 2021 12:36
Aan: HenriWahl/Nagstamon ***@***.***>
CC: Yperman Hans (112) ***@***.***>; Comment ***@***.***>
Onderwerp: Re: [HenriWahl/Nagstamon] Zabbix connection is not restored when host not found on startup. (#650)
Urgentie: Laag


Sorry for the really late reply... can you please check if this still is valid for latest 3.6.0 and in the best case create a pull request to get in into easily?

-

**Closed** 2021-09-30 20:30 UTC
