### ISSUE TITLE
Check_MK and disabled notifications

### ISSUE THREAD

**Issue by ciberconceito** [HenriWahl/Nagstamon#201] opened 2016-02-25 11:50 UTC
Good morning,

I have a monitoring server with check_mk and one of my services (check_mk_agent) keeps timing out on one specific server.
I have set the service with disabled notification, and on anag (android app) i don't get alerts and the critical doesn't bother me. 
However on nagstamon, it keeps popping up as critical. It is a big problem because i spend the day with a critical warning popping up every 2-4 minutes and i'm starting to ignore the alerts.

Need help.

Tiago Fernandes

**Comment by tyhawk** [comment] 2016-02-25 12:06
This seems to be a duplicate of issue #132

**Comment by ciberconceito** [comment] 2016-02-25 14:09
Ty, i was looking for this and i couldn't find it.

**Closed** 2016-04-25 06:23 UTC
