### ISSUE TITLE
Direct crash after clicking on OK from Create new server

### ISSUE THREAD

**Issue by bphd** [HenriWahl/Nagstamon#516] opened 2018-10-24 07:36 UTC
```
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2018-10-24T07:40:29.000000000Z" /> 
  <EventRecordID>76853</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer></Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>Nagstamon.exe</Data> 
  <Data>0.0.0.0</Data> 
  <Data>00000000</Data> 
  <Data>ucrtbase.DLL</Data> 
  <Data>10.0.10586.1171</Data> 
  <Data>59ae5010</Data> 
  <Data>40000015</Data> 
  <Data>00000000000699df</Data> 
  <Data>10ac</Data> 
  <Data>01d46b6cbc9bf015</Data> 
  <Data>C:\temp\Nagstamon-3.0.1-win64\Nagstamon.exe</Data> 
  <Data>C:\windows\system32\ucrtbase.DLL</Data> 
  <Data>13f5f823-d760-11e8-863c-d8d385764f4d</Data> 
  </EventData>
  </Event>
```

**Comment by mprenditore** [comment] 2018-10-24 08:16
Nagstamon logs will be useful to better understand the issue.

**Comment by bphd** [comment] 2018-10-24 08:33
I haven't any

**Comment by HenriWahl** [comment] 2018-10-24 12:13
Please enable debugging in Settings. 

Also a good idea might be to use a newer version than the 3.0.1 - see https://nagstamon.ifw-dresden.de/download/ for more options.

**Comment by bphd** [comment] 2018-10-24 12:43
debug mode doesn't generate any log at all, blank log
And it's the same at the latest testing version

**Comment by HenriWahl** [comment] 2018-10-24 17:08
Which Windows version do you use? Which server did you try to configure?

**Comment by bphd** [comment] 2018-10-24 17:15
Windows 7, Centreon

**Comment by HenriWahl** [comment] 2018-10-25 05:09
Are you able to run Nagstamon in a console (cmd.exe) from sources as in https://nagstamon.ifw-dresden.de/docs/requirements/ to get some output?

**Comment by bphd** [comment] 2018-10-25 07:20
Only for Centreon

**Comment by bphd** [comment] 2018-10-25 08:32
I haven't "C:\python36"

**Comment by HenriWahl** [comment] 2018-10-26 05:12
Would it be possible to install Python for testing?

**Comment by BenoitPoulet** [comment] 2018-10-26 08:36
Hello @bphd 
Also, can you post the screenshot of your config for the server type Centreon , just before saving the config ? (**with the checkbox "Show more options" checked**)

Thanks

**Comment by bphd** [comment] 2018-10-26 08:48
I have Python installed

**Comment by bphd** [comment] 2018-10-26 08:50
Salut @BenoitPoulet !

Non, the serv. settings are confidential. What you want to know about ?

And i have to say that the soft crash regardless of what i type on the form. A blank form result in a instant crash too

**Comment by BenoitPoulet** [comment] 2018-10-26 09:16
@bphd Of course details are confidential, but you can anonymise the data....

**Comment by BenoitPoulet** [comment] 2018-10-26 14:04
Can't reproduce with 3.0.2 under Windows 10 :
I only changed the server address with the Centreon's demo server :
![capture](https://user-images.githubusercontent.com/2464712/47571285-78083580-d938-11e8-8d4e-1b2c11945870.PNG)

Last thing is to checkout the Git, and launch Nagstamon by hand with Python as @HenriWahl suggest.

**Comment by bphd** [comment] 2018-10-26 14:08
I haven't "C:\python36"

It's exacly like your screen, just i don't have the left window. I can type what i want in the right window, when i click OK it automaticaly crash

**Comment by BenoitPoulet** [comment] 2018-10-26 14:11
Try to update to 3.0.2, you are using 3.0.1 => https://nagstamon.ifw-dresden.de/download/

**Comment by HenriWahl** [comment] 2018-12-10 19:53
Please check with latest release candidate 3.1.99rc2 because former binaries had problems with latest Python keyring module. Now I chose to use an older one and found it more stable.

**Comment by bphd** [comment] 2019-01-02 08:14
Same with 3.2, crash after clicking OK

**Comment by BenoitPoulet** [comment] 2019-01-07 09:04
Can you provided the anonymized Nagstamon debug log ? (without log or console log, we cannot debug)

**Comment by bphd** [comment] 2019-01-07 10:00
Comment i'm supposed to do that ?

**Comment by bphd** [comment] 2019-04-03 11:44
Some update about that concern.

All people in my office have the same problem (Windows 7 and Windows 10)

Just one person in my office hasn't any problem. We've all taked his "%USERPROFILE%/.nagstamon/server_Monitor server.conf" and now it finally work for all of us.

I want to locate the concern to correct the problem in the next update of Nagstamon, i have thinked about making a `diff` between my files and the working files. But it appears that it's the first config. windows who make problems. And if we not pass this window, no files are created. So i haven't anything to compare why this file works. But it appears that if we get around the first window, the software seems to work.

Any idea ?

**Comment by HenriWahl** [comment] 2019-04-03 12:37
Which version do you use? Can you try latest testing please from https://nagstamon.ifw-dresden.de/download/#testing ?

**Comment by bphd** [comment] 2019-04-04 07:21
Sure, and how can i help to report the problem ?

**Comment by HenriWahl** [comment] 2019-04-04 11:58
The best solution would be you installed Python and its dependencies as described on https://nagstamon.ifw-dresden.de/docs/requirements/.

Then get you the sourcecode from Github.

After this run nagstamon.py in a commandline windows so we could get all output necessary.

If you need help let me know.

**Comment by bphd** [comment] 2019-04-04 12:11
`?:\Users\?>python ?:\temp\Nagstamon-master\nagstamon.py
Warning: QT_DEVICE_PIXEL_RATIO is deprecated. Instead use:
   QT_AUTO_SCREEN_SCALE_FACTOR to enable platform plugin controlled per-screen f
actors.
   QT_SCREEN_SCALE_FACTORS to set per-screen factors.
   QT_SCALE_FACTOR to set the application global scale factor.
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a la
yout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a la
yout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a la
yout
Traceback (most recent call last):
  File "?:\temp\Nagstamon-master\Nagstamon\Servers\Centreon.py", line 253, in _g
et_sid
    sid = self.session.cookies['PHPSESSID']
  File "?:\Users\?\AppData\Local\Programs\Python\Python37-32\lib\si
te-packages\requests\cookies.py", line 328, in __getitem__
    return self._find_no_duplicates(name)
  File "?:\Users\?\AppData\Local\Programs\Python\Python37-32\lib\si
te-packages\requests\cookies.py", line 399, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='PHPSESSID', domain=None, path=None"
Traceback (most recent call last):
  File "?:\temp\Nagstamon-master\Nagstamon\QUI\__init__.py", line 5781, in ok
    statuswindow.servers_vbox.addLayout(statuswindow.create_ServerVBox(servers[s
elf.server_conf.name]))
  File "?:\temp\Nagstamon-master\Nagstamon\QUI\__init__.py", line 1348, in creat
e_ServerVBox
    server_vbox = ServerVBox(server, parent=self)
  File "?:\temp\Nagstamon-master\Nagstamon\QUI\__init__.py", line 2824, in __ini
t__
    self.table = TreeView(len(HEADERS) + 1, 0, sort_column, sort_order, self.ser
ver, parent=parent)
  File "?:\temp\Nagstamon-master\Nagstamon\QUI\__init__.py", line 3205, in __ini
t__
    self.worker = self.Worker(server=server, sort_column=self.sort_column, sort_
order=self.sort_order)
  File "?:\temp\Nagstamon-master\Nagstamon\QUI\__init__.py", line 3960, in __ini
t__
    self.server.init_config()
  File "?:\temp\Nagstamon-master\Nagstamon\Servers\Centreon.py", line 74, in ini
t_config
    self._define_url()
  File "?:\temp\Nagstamon-master\Nagstamon\Servers\Centreon.py", line 415, in _d
efine_url
    'xml_services': self.monitor_cgi_url + '/include/monitoring/status/Services/
' + self.XML_PATH + '/serviceXML.php',
AttributeError: 'CentreonServer' object has no attribute 'XML_PATH'`

**Comment by HenriWahl** [comment] 2019-04-05 08:46
@BenoitPoulet - any idea? Or opportunity to test?

**Comment by HenriWahl** [comment] 2019-04-12 08:05
@bphd which version of Centreon do you currently use?

**Comment by bphd** [comment] 2019-04-12 09:27
18.10

**Comment by HenriWahl** [comment] 2019-04-12 19:06
I think i found some trace and tried to fix it. Please have a look at https://nagstamon.ifw-dresden.de/files/incoming/ and test if there is any improvement.

**Comment by HenriWahl** [comment] 2019-04-15 10:26
@bphd where you able to test this fix?

**Comment by BenoitPoulet** [comment] 2019-04-15 15:32
@HenriWahl Hello, sorry they changed my e-mail reader to Outlook, i'm so confused by this software, i missed your notification.

Your changes seems ok to me, let see if it's ok for @bphd

**Comment by bphd** [comment] 2019-04-15 15:43
I have to wait 1 week to test

**Comment by HenriWahl** [comment] 2019-04-15 19:02
@BenoitPoulet OK man, I hope I did not destroy something. Condolence due to Outlook...

**Comment by bphd** [comment] 2019-04-23 08:16
It's HenriWahl's software, no ? Why is he afraid to break it and ask for an other person to check ?

Now the software does not crash, it shows "Monitor URL invalid" or "Empty host XML result"

```python
DEBUG: SystemTrayIcon created icon <PyQt5.QtGui.QIcon object at 0x041DA8F0> for state "OK"
DEBUG: SystemTrayIcon created icon <PyQt5.QtGui.QIcon object at 0x041DA8A0> for state "INFORMATION"
DEBUG: SystemTrayIcon created icon <PyQt5.QtGui.QIcon object at 0x041DA940> for state "UNKNOWN"
DEBUG: SystemTrayIcon created icon <PyQt5.QtGui.QIcon object at 0x041DA990> for state "WARNING"
DEBUG: SystemTrayIcon created icon <PyQt5.QtGui.QIcon object at 0x041DA9E0> for state "AVERAGE"
DEBUG: SystemTrayIcon created icon <PyQt5.QtGui.QIcon object at 0x041DAA30> for state "HIGH"
DEBUG: SystemTrayIcon created icon <PyQt5.QtGui.QIcon object at 0x041DAA80> for state "CRITICAL"
DEBUG: SystemTrayIcon created icon <PyQt5.QtGui.QIcon object at 0x041DAAD0> for state "DISASTER"
DEBUG: SystemTrayIcon created icon <PyQt5.QtGui.QIcon object at 0x041DAB20> for state "UNREACHABLE"
DEBUG: SystemTrayIcon created icon <PyQt5.QtGui.QIcon object at 0x041DAB70> for state "DOWN"
DEBUG: SystemTrayIcon created icon <PyQt5.QtGui.QIcon object at 0x041DABC0> for state "ERROR"
DEBUG: 2019-04-23 10:01:01.119252 Saving configuration to file ?:\users\?\.nagstamon\nagstamon.conf
DEBUG: 2019-04-23 10:01:01.135252 Saving configuration to file ?:\users\?\.nagstamon\nagstamon.conf
DEBUG: 2019-04-23 10:01:01.137252 leNomDuMonitor Refreshing all hosts and services
DEBUG: 2019-04-23 10:01:01.948252 leNomDuMonitor Checking session status
DEBUG: 2019-04-23 10:01:01.948252 leNomDuMonitor URLs defined for Centreon 18.1
DEBUG: 2019-04-23 10:01:01.948252 leNomDuMonitor FetchURL: http://?/centreon/api/internal.php?object=centreon_keepalive&action=keepAlive CGI Data: None
DEBUG: 2019-04-23 10:01:02.025252 leNomDuMonitor Session status : "Unauthorized"
DEBUG: 2019-04-23 10:01:02.026252 leNomDuMonitor FetchURL: http://?/centreon/include/monitoring/status/Hosts/xml/hostXML.php?num=0&limit=9999&o=hpb&p=20202&criticality=0&statusHost=hpb&sSetOrderInMemory=1&sid=? CGI Data: None
DEBUG: 2019-04-23 10:01:02.135252 leNomDuMonitor Empty host XML result
DEBUG: 2019-04-23 10:01:16.079379 leNomDuMonitor Open monitor web page http://?/centreon/main.php?
DEBUG: 2019-04-23 10:02:02.141984 leNomDuMonitor Checking session status
DEBUG: 2019-04-23 10:02:02.141984 leNomDuMonitor URLs defined for Centreon 18.1
DEBUG: 2019-04-23 10:02:02.141984 leNomDuMonitor FetchURL: http://?/centreon/api/internal.php?object=centreon_keepalive&action=keepAlive CGI Data: None
DEBUG: 2019-04-23 10:02:02.220992 leNomDuMonitor Session status : "Unauthorized"
DEBUG: 2019-04-23 10:02:02.220992 leNomDuMonitor FetchURL: http://?/centreon/include/monitoring/status/Hosts/xml/hostXML.php?num=0&limit=9999&o=hpb&p=20202&criticality=0&statusHost=hpb&sSetOrderInMemory=1&sid=? CGI Data: None
DEBUG: 2019-04-23 10:02:02.328003 leNomDuMonitor Empty host XML result
DEBUG: 2019-04-23 10:03:02.335003 leNomDuMonitor Checking session status
DEBUG: 2019-04-23 10:03:02.335003 leNomDuMonitor URLs defined for Centreon 18.1
DEBUG: 2019-04-23 10:03:02.335003 leNomDuMonitor FetchURL: http://?/centreon/api/internal.php?object=centreon_keepalive&action=keepAlive CGI Data: None
DEBUG: 2019-04-23 10:03:02.412011 leNomDuMonitor Session status : "Unauthorized"
DEBUG: 2019-04-23 10:03:02.412011 leNomDuMonitor FetchURL: http://?/centreon/include/monitoring/status/Hosts/xml/hostXML.php?num=0&limit=9999&o=hpb&p=20202&criticality=0&statusHost=hpb&sSetOrderInMemory=1&sid=? CGI Data: None
DEBUG: 2019-04-23 10:03:02.522022 leNomDuMonitor Empty host XML result
DEBUG: 2019-04-23 10:03:34.582227 leNomDuMonitor Created server.
DEBUG: 2019-04-23 10:03:34.587228 leNomDuMonitor FetchURL: http://?/index.php CGI Data: None
DEBUG: 2019-04-23 10:03:34.593229 leNomDuMonitor Centreon version unknown : supposed to be >= 18.10
DEBUG: 2019-04-23 10:03:34.593229 leNomDuMonitor FetchURL: http://?/index.php CGI Data: None
DEBUG: 2019-04-23 10:03:34.595229 leNomDuMonitor Password login : ? : ?
ERROR: 2019-04-23 10:03:34.599229 leNomDuMonitor Traceback (most recent call last):
  File "?:\temp\Nagstamon-master\Nagstamon\Servers\Centreon.py", line 255, in _get_sid
    sid = self.session.cookies['PHPSESSID']
  File "?:\Users\?\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\cookies.py", line 328, in __getitem__
    return self._find_no_duplicates(name)
  File "?:\Users\?\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\cookies.py", line 399, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='PHPSESSID', domain=None, path=None"

DEBUG: 2019-04-23 10:03:34.599229 leNomDuMonitor URLs defined for Centreon 18.1
DEBUG: 2019-04-23 10:03:34.635233 leNomDuMonitor Checking session status
DEBUG: 2019-04-23 10:03:34.635233 leNomDuMonitor URLs defined for Centreon 18.1
DEBUG: 2019-04-23 10:03:34.635233 leNomDuMonitor FetchURL: http://?/api/internal.php?object=centreon_keepalive&action=keepAlive CGI Data: None
DEBUG: 2019-04-23 10:03:34.637233 leNomDuMonitor Session status : <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /api/internal.php was not found on this server.</p>
</body></html>

DEBUG: 2019-04-23 10:03:34.638233 leNomDuMonitor FetchURL: http://?/include/monitoring/status/Hosts/xml/hostXML.php?num=0&limit=9999&o=hpb&p=20202&criticality=0&statusHost=hpb&sSetOrderInMemory=1&sid=ERROR CGI Data: None
DEBUG: 2019-04-23 10:03:36.147384 Saving configuration to file ?:\users\?\.nagstamon\nagstamon.conf
DEBUG: 2019-04-23 10:03:36.161385 Saving configuration to file ?:\users\?\.nagstamon\nagstamon.conf
DEBUG: 2019-04-23 10:03:36.164386 leNomDuMonitor Refreshing all hosts and services
DEBUG: 2019-04-23 10:03:36.643434 leNomDuMonitor Checking session status
DEBUG: 2019-04-23 10:03:36.643434 leNomDuMonitor URLs defined for Centreon 18.1
DEBUG: 2019-04-23 10:03:36.643434 leNomDuMonitor FetchURL: http://?/api/internal.php?object=centreon_keepalive&action=keepAlive CGI Data: None
DEBUG: 2019-04-23 10:03:36.646434 leNomDuMonitor Session status : <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /api/internal.php was not found on this server.</p>
</body></html>

DEBUG: 2019-04-23 10:03:36.646434 leNomDuMonitor FetchURL: http://?/include/monitoring/status/Hosts/xml/hostXML.php?num=0&limit=9999&o=hpb&p=20202&criticality=0&statusHost=hpb&sSetOrderInMemory=1&sid=ERROR CGI Data: None
DEBUG: 2019-04-23 10:04:07.967566 leNomDuMonitor Created server.
DEBUG: 2019-04-23 10:04:07.972566 leNomDuMonitor FetchURL: http://?/centreon/index.php CGI Data: None
DEBUG: 2019-04-23 10:04:08.166586 leNomDuMonitor Centreon version detected : 18.10
DEBUG: 2019-04-23 10:04:08.166586 leNomDuMonitor FetchURL: http://?/centreon/index.php CGI Data: None
DEBUG: 2019-04-23 10:04:08.351604 leNomDuMonitor FetchURL: http://?/centreon/index.php CGI Data: {'centreon_token': '?', 'submitLogin': 'Connect', 'useralias': '?', 'password': '?'}
DEBUG: 2019-04-23 10:04:08.543623 leNomDuMonitor Password login : ? : ?
DEBUG: 2019-04-23 10:04:08.543623 leNomDuMonitor SID : ?
DEBUG: 2019-04-23 10:04:08.543623 leNomDuMonitor Only Centreon Broker is supported in Centeon >= 2.7 -> XML_PATH=xml
DEBUG: 2019-04-23 10:04:08.543623 leNomDuMonitor URLs defined for Centreon 18.1
DEBUG: 2019-04-23 10:04:08.543623 leNomDuMonitor Checking session status
DEBUG: 2019-04-23 10:04:08.543623 leNomDuMonitor URLs defined for Centreon 18.1
DEBUG: 2019-04-23 10:04:08.543623 leNomDuMonitor FetchURL: http://?/centreon/api/internal.php?object=centreon_keepalive&action=keepAlive CGI Data: None
DEBUG: 2019-04-23 10:04:08.618631 leNomDuMonitor Session status : "Unauthorized"
```

**Comment by HenriWahl** [comment] 2019-04-23 08:57
@bphd - the Centreon part is maintained by @BenoitPoulet.

**Comment by BenoitPoulet** [comment] 2019-04-30 07:49
Hello, i was in vacation, i will have a look shortly.

Can you tell me 2 infos please ?

- which centreon version are you using ?
- did you customize the centreon's home page (the login page) ?

**Comment by bphd** [comment] 2019-04-30 07:51
https://github.com/HenriWahl/Nagstamon/issues/516#issuecomment-482505757

No

**Comment by BenoitPoulet** [comment] 2019-04-30 14:30
I think i successfully replicate your problem.

1) your URL seems to be : **http://?/centreon** , so please set it correctly
2)  you get immediately, after saving your conf :  "Session status : "Unauthorized""
and just after : "Empty host XML result".
That means Nagstamon cannot open a valid session on your Centreon. Either your credentials are not valid, either the account do not have access to the web interface. ("Reach Centreon Front-end" in the user's conf in Centreon)

When the debug is enabled and your credentials are correct you must see "Session status : null" in the log.

Yes, the message shown in Nagstamon is not clear in this case, i will see if i can show a better one.

You are welcome to help me with this server support and enhance the class, as i'm not a dev, i do as much as i can. Any help is appreciated.

**Comment by bphd** [comment] 2019-04-30 14:33
Ignore les "?" je les ai moi même ajoutés au log

J'utilise le compte superadmin habituel avec les bons identifiants

J'en suis pas un non plus figures-toi, j'vais pas pouvoir plus aider à ce niveau

**Comment by HenriWahl** [comment] 2019-12-18 20:36
Any improvement in sight when using 3.4rc2?

**Comment by bphd** [comment] 2019-12-18 20:39
I'm not in the same enterprise anymore, maybe the problem still, I don't know
But when I used this software I was used to copy the configuration file from my colleague computer to mine to make Nagstamon work

**Comment by HenriWahl** [comment] 2019-12-18 20:41
Ok... So I will close this issue.

**Closed by HenriWahl** 2019-12-18 20:41 UTC
