### ISSUE TITLE
nagstamon and flite voice

### ISSUE THREAD

**Issue by xevilstar** [HenriWahl/Nagstamon#450] opened 2017-10-04 11:54 UTC
Hello and thanks for existing,

I find your program very useful and lifesaving.
I tried to implement some flite (http://www.speech.cs.cmu.edu/flite/) actions . 
the same identical string :

/usr/bin/lxterminal -e /usr/bin/flite -voice slt -t "$ADDRESS$ $SERVICE$ The situation is $STATUS-INFO$"

works with the "actions" but if I put it in the custom notifications actions the variables seem to be empty.
I am obviously missing something here.........
can you help me fill in the gaps please.

Thanks :)

**Comment by HenriWahl** [comment] 2017-10-06 08:40
Sorry the tooltip is wrong here. Was intended as you expected but is not implemented yet. Please see https://github.com/HenriWahl/Nagstamon/issues/308 - somebody had the same problem.

**Comment by HenriWahl** [comment] 2020-12-22 11:39
Well, nothing new here so closing for now.

**Closed by HenriWahl** 2020-12-22 11:39 UTC
