### ISSUE TITLE
Erroneuously places status info with two displays and Cinnamon DE

### ISSUE THREAD

**Issue by Fjodor42** [HenriWahl/Nagstamon#625] opened 2020-01-29 12:49 UTC
Hiya,

I don't know which of the factors make the difference, but since 3.4, the status window is shown at the bottom right of the primary display, which, for me, is the rightmost one.

With 3.4.1, it even protrudes into the leftmost one.

Screenshots are attached.

Console output is as follows, for starting Nagstamon, clicking to show the status window, and then exiting from right-click menu, although the part starting with `Qt has` was only shown with 3.4.1:

```
smo@dell-smo:~$ nagstamon
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
QLayout: Attempting to add QLayout "" to StatusWindow "", which already has a layout
Qt has caught an exception thrown from an event handler. Throwing
exceptions from an event handler is not supported in Qt.
You must not let any exception whatsoever propagate through Qt code.
If that is not possible, in Qt 5 you must at least reimplement
QCoreApplication::notify() and catch all exceptions there.
```

I have only tested 3.4.1 with the left display being 4K and the rightmost one being 2560*1440, but the erroneous display with 3.4 is present both in that configuration and with two 4K displays.

OS is Linux 19.04 Disco Dingo with Cinnamon 3.8.8 from the normal Ubuntu repo.

X is Xorg 1.20

Graphics is Intel (`xserver-xorg-video-intel/now 2:2.99.917+git1903011933.6afed3~oibaf~c amd64 [installed,local]` from http://ppa.launchpad.net/oibaf/graphics-drivers/ubuntu

![nagstamon-3 4 1_001](https://user-images.githubusercontent.com/1410995/73357627-105c3b00-429d-11ea-94bf-621513708bdb.png)
![nagstamon-3 4_001](https://user-images.githubusercontent.com/1410995/73357628-105c3b00-429d-11ea-8c6d-eee30f874a47.png)

Please let me know if you need any additional info (and, obviously, what that might be ).

Best regards,

Sune Mølgaard

**Comment by HenriWahl** [comment] 2020-01-29 15:01
Hi Sune,

Well, the 3.4 change finally fixed the Cinnamon version to display the status window as it was intended - near the systray icon.

3.4.1 now supports high resolution displays (to fix https://github.com/HenriWahl/Nagstamon/issues/618) which is the only change that happened regarding the GUI. Apparently this leads to your problem - at least I do assume.

This change is in https://github.com/HenriWahl/Nagstamon/commit/1aa901e322ac05ed361e465e357df424c040fee5#diff-7492e72ab345fadd73274d937f364305R117.

To prove this theory you could checkout the sources and comment the lines 117 and 118 to disable high resolution awareness (https://github.com/HenriWahl/Nagstamon/blob/master/Nagstamon/QUI/__init__.py#L117).

**Comment by Fjodor42** [comment] 2020-01-29 16:10
Hi Henrik,

Thank you for your speedy reply :-)

I can confirm that commenting lines 117 and 118 makes 3.4.1 behave in the same way as 3.4 with regards to the GUI, meaning that it stays within the smaller primary display, and isn't needlessly high, so theory confirmed, I guess :-)

I will try to uncomment again when I get home to my 4K primary to see if it behaves better there, but do I assume correctly that this is now a PyQT5 bug regarding handling of mixes of regular and high DPI displays?

Also, could you point me in the direction of the changes in 3.4 that had to do with status window placement (and Cinnamon)?

Best regards,

Sune Mølgaard

**Comment by HenriWahl** [comment] 2020-01-29 16:39
> I can confirm that commenting lines 117 and 118 makes 3.4.1 behave in the same way as 3.4 with regards to the GUI, meaning that it stays within the smaller primary display, and isn't needlessly high, so theory confirmed, I guess :-)

At least something...

> I will try to uncomment again when I get home to my 4K primary to see if it behaves better there, but do I assume correctly that this is now a PyQT5 bug regarding handling of mixes of regular and high DPI displays?

Quite possible - I am not able to confirm due to the lack of 4K display.

> Also, could you point me in the direction of the changes in 3.4 that had to do with status window placement (and Cinnamon)?

Of course: 
https://github.com/HenriWahl/Nagstamon/blob/master/Nagstamon/Config.py#L58 and
https://github.com/HenriWahl/Nagstamon/blob/master/Nagstamon/QUI/__init__.py#L1773

Maybe there should be an option in settings to avoid such workarounds.

**Comment by Fjodor42** [comment] 2020-01-29 17:07
Thank you again :-)

Adding `DESKTOP_CINNAMON = False` just below the if-else-block makes it behave like it should :-)

That being said, you may have noted that I am on Ubuntu 19.04 with Cinnamon 3.8.8...

19.04 is EOL soon, and so I should upgrade shortly, and at that point, it shall be interesting to see if I suddenly need the workaround that I just disabled.

18.04 (and even 16.04) will live on for some time yet, though, so maybe some detection of Cinnamon *version* (as well as identifiying from what version the workaround is needed) might be a way forward...

Anyway: I will let you decide whether to close this Issue or not, i.e. whether some code should result, but thank you so far :-)

**Comment by HenriWahl** [comment] 2020-01-31 07:37
Well, I think there will be too much efford to check several versions of Cinnamon - at least for me. 
I am happy to merge code contributions... :-)

**Comment by Fjodor42** [comment] 2020-01-31 10:22
Quite fair :-)

I'll see if I can find the time to whip anything up.

Btw., I tried uncommenting the commented HighDPI stuff while on 2 * 4K.

That resulted in a large, empty status window on the wrong display, but whether this is due to (old) Cinnamon, or due to PyQT5 not working well with multiple displays, I cannot say.

**Comment by Slydder** [comment] 2020-08-19 17:18
I have a dual monitor setup and this is what mine looks like on Mint 20 "Ulyana"

![Screenshot from 2020-08-19 18-55-10](https://user-images.githubusercontent.com/1515201/90668655-b16a0d80-e250-11ea-8336-be20cc0221d9.png)

**Comment by HenriWahl** [comment] 2020-12-22 14:59
No real cure for that... closing issue in hope of a pull request.

**Closed by HenriWahl** 2020-12-22 14:59 UTC
