### ISSUE TITLE
window won't open from systray icon

### ISSUE THREAD

**Issue by oernii** [HenriWahl/Nagstamon#353] opened 2017-01-19 15:28 UTC
Beginning with version 2.1 nagstamon window does not open after some time (a few hours) after clicking on the systray icon.

I have to use this workaround: restart nagstam or switch to floating bar and back to icon.

There are no logs in console when this happens. Any idea how to debug this?

PS: fedora 25, cinnamon, nagstamon-2.1.post20161129

**Comment by HenriWahl** [comment] 2017-01-19 19:02
Strange... we need to compare changes made since 2.0.1 regarding systray and popup.

At https://www.linuxmint.com/rel_rosa_cinnamon_whatsnew.php I read there are changes in system tray - they now support indicators as in Ubuntu. Maybe you can play around with these settings?

**Comment by ndias** [comment] 2017-02-13 11:01
I also have this problem, I'm using also Fedora 25 but with gnome-shell with the extension TopIcons Plus.
If I enable the debug mode and restart this doesn't happen.

**Comment by mprenditore** [comment] 2017-02-13 11:04
@ndias I'm on Fedora 25 with gnome-shell on Xorg (but I tried also on Wayland) with extension TopIcons Plus and I don't have the problem. If you let it opened in debug mode does it fire the error? in that case, could you please provide the debug file? Thank you

**Comment by HenriWahl** [comment] 2017-02-13 11:31
Since your issue report I run my Nagstamon in systray mode on Fedora 25 GNOME Xorg too but did not yet have this effect. Seems hard to debug...

**Comment by ndias** [comment] 2017-02-13 12:11
@mprenditore Like I wrote in the last line, no, if I opened in debug mode the error doesn't happen, so, because  everything works as expected in debug mode no error is visible in the debug file.

**Comment by mprenditore** [comment] 2017-02-13 13:24
@ndias ok, so I'll try to execute it without debug mode enabled.
Just another couple of questions, which kind of servers are you monitoring? And, are you using last commit or last compiled version downlodable?

**Comment by ndias** [comment] 2017-02-13 14:26
@mprenditore I'm monitoring a nagios server, but I think this is not related, even when I lost the connection to the server (when nagstamon is working as expected), I can open the status window and I can see an error message, but with this, I can't open the window, one strange thing is, I can use the right button mouse to see the options and select (although selecting "show status window", do nothing).
I first saw the problem in version 2.0.1 right now I'm using nagstamon-2.1.post20161129-1.noarch

**Comment by oernii** [comment] 2017-02-13 14:32
Running in debug mode didn't help me. Also after a time nagstamon always takes focus when changing workspaces, even if in systray mode. After restarting it, systray is ok and so is the focus.

PS: fedora 25, cinnamon, 1x nagios server. nagstamon-2.1.post20161129-1.noarch.rpm

**Comment by HenriWahl** [comment] 2017-02-27 09:15
No solution yet but I can confirm that *sometimes* I have this effect *out-of-a-sudden* too. :-(

**Comment by mprenditore** [comment] 2017-02-27 09:17
I can confirm too... But from what I saw, it happen if there is some network problem... there is some problem handling exceptions on network problems (at least with centreon).. I'm working to solve them but didn't finished yet...

**Comment by HenriWahl** [comment] 2017-08-02 14:29
I did not have it for a while now with the latest commits. How is it on your desktop?

**Comment by ndias** [comment] 2017-11-18 10:18
It seems something happen because right now I don't have the problem anymore.
I'm on Fedora 26, last time I comment on the bug I was in Fedora 25.

**Comment by HenriWahl** [comment] 2017-11-18 12:39
So lets close this issue, hoping there won't be a reason to reopen it.

**Closed by HenriWahl** 2017-11-18 12:39 UTC
