### ISSUE TITLE
Nagstamon2 not 'always on top'

### ISSUE THREAD

**Issue by alekksi** [HenriWahl/Nagstamon#222] opened 2016-04-14 08:05 UTC
I have issues with the new nagstamon build often falling behind other windows. Sometimes it can be rectified by just re-gaining focus on nagstamon, other times I have to restart the application.

Using version Nagstamon-2.0-alpha-20160307-win64 on Windows 7

**Comment by HenriWahl** [comment] 2016-04-14 08:50
I heard of such behaviour too but did not yet find any pattern. Are there some actions correlating to this behavior like a lock screen or any other window management related tasks?

**Comment by HenriWahl** [comment] 2016-04-25 19:05
Is Nagstamon in such a case still running or crashed completely?

**Comment by alekksi** [comment] 2016-04-25 19:28
It is still running in this case and can be brought back to the top
sometimes by regaining focus on it

**Comment by HenriWahl** [comment] 2016-04-27 15:57
Please check latest 20160427 binary from https://nagstamon.ifw-dresden.de/nagstamon-20/

**Comment by HenriWahl** [comment] 2016-05-03 14:27
Is there any progress noticeable?

**Comment by alekksi** [comment] 2016-05-03 14:38
Sorry just got back from holiday, testing latest beta now. Will revert
shortly.

Cheers!

**Comment by edbergavera** [comment] 2016-05-04 16:26
Hi,

I have the same issue with @alekksi. I'm using 2.0 BETA-20160429 on Win7. Nagstamon seems to go behind all windows but it is still functional. It becomes visible on top of all other windows by simply focusing your mouse on it.

**Comment by HenriWahl** [comment] 2016-05-04 21:34
Was there a version where this did not happen?

**Comment by edbergavera** [comment] 2016-05-04 22:25
Hi Henri,

So far the version that I have no issues like this is the latest stable
version 1.0.1.

On Thu, May 5, 2016 at 5:34 AM, Henri Wahl <notifications@github.com> wrote:

> Was there a version where this did not happen?
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/HenriWahl/Nagstamon/issues/222#issuecomment-217010795>
>



-- 
*Eduardo D. Bergavera, Jr.*
Linux Admin
Email: edbergavera@gmail.com
OpenID: https://launchpad.net/~edbergavera
Github: https://github.com/edbergavera

**Comment by HenriWahl** [comment] 2016-05-09 10:07
Please check latest versions for Windows:
https://nagstamon.ifw-dresden.de/files-nagstamon/unstable/Nagstamon-2.0-beta-20160509-win32_setup.exe
https://nagstamon.ifw-dresden.de/files-nagstamon/unstable/Nagstamon-2.0-beta-20160509-win64_setup.exe

**Comment by edbergavera** [comment] 2016-05-09 11:26
Thanks Henri! Will try this out and update you via this email.

On Monday, 9 May 2016, Henri Wahl <notifications@github.com> wrote:

> Please check latest versions for Windows:
>
> https://nagstamon.ifw-dresden.de/files-nagstamon/unstable/Nagstamon-2.0-beta-20160509-win32_setup.exe
>
> https://nagstamon.ifw-dresden.de/files-nagstamon/unstable/Nagstamon-2.0-beta-20160509-win64_setup.exe
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/HenriWahl/Nagstamon/issues/222#issuecomment-217825682>
>


-- 
*Eduardo D. Bergavera, Jr.*
Linux Admin
Email: edbergavera@gmail.com
OpenID: https://launchpad.net/~edbergavera
Github: https://github.com/edbergavera

**Comment by HenriWahl** [comment] 2016-05-11 13:07
Please check latest BETA 20160511 from https://nagstamon.ifw-dresden.de/nagstamon-20/ - the previous version did not work as expected.

**Comment by edbergavera** [comment] 2016-05-11 14:34
Thanks for the update Henri.

On Wed, May 11, 2016 at 9:07 PM, Henri Wahl <notifications@github.com>
wrote:

> Please check latest BETA 20160511 from
> https://nagstamon.ifw-dresden.de/nagstamon-20/ - the previous version did
> not work as expected.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/HenriWahl/Nagstamon/issues/222#issuecomment-218453481>
>



-- 
*Eduardo D. Bergavera, Jr.*
Linux Admin
Email: edbergavera@gmail.com
OpenID: https://launchpad.net/~edbergavera
Github: https://github.com/edbergavera

**Comment by HenriWahl** [comment] 2016-05-12 05:34
New insights:
- all my attempts are in vain - whatever combo of window flags I use, it does not help
- the only reproducible thing I found right now is starting the nagstamon.exe inside its folder and as soon as possible give focus to another window so the Nagstamon window is not on top and thus apparently is not able to get eternal top-ness

So my question is: how do you start Nagstamon?

**Comment by edbergavera** [comment] 2016-05-12 06:40
Hi Henri,

I installed and tested the latest beta today on my work computer and so far
I haven't not encountered an issue where Nagstamon loses its focus or fails
behind application windows. Tested it for 9 hours during my work thus far.
I will continue to update any progress here regarding this issue.

Kudos to you guys!




On Thu, May 12, 2016 at 1:34 PM, Henri Wahl <notifications@github.com>
wrote:

> New insights:
>
>    - all my attempts are in vain - whatever combo of window flags I use,
>    it does not help
>    - the only reproducible thing I found right now is starting the
>    nagstamon.exe inside its folder and as soon as possible give focus to
>    another window so the Nagstamon window is not on top and thus apparently is
>    not able to get eternal top-ness
>
> So my question is: how do you start Nagstamon?
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/HenriWahl/Nagstamon/issues/222#issuecomment-218664351>
>



-- 
*Eduardo D. Bergavera, Jr.*
Linux Admin
Email: edbergavera@gmail.com
OpenID: https://launchpad.net/~edbergavera
Github: https://github.com/edbergavera

**Comment by HenriWahl** [comment] 2016-05-12 11:02
The last attempt was a fail. But NOW(tm) there seems to be a final solution. If not I am running out of ideas aside installing another OS. Please check the 20160512 files.

**Comment by HenriWahl** [comment] 2016-05-12 14:26
Even the 20160512 seems to vanish from time to time... :-( please check the latest 20160513.

**Comment by alekksi** [comment] 2016-05-12 15:22
I've not been having the issue recently on the previous beta, updated and
testing again on 0513 version

**Comment by HenriWahl** [comment] 2016-05-12 16:46
This sounds great - but I had that trouble again, so as a last resort I hope the 20160513 will fix this, pumping even more dirty workarounds into it :-(

**Comment by edbergavera** [comment] 2016-05-12 22:22
Testing  20160513 today.

On Friday, 13 May 2016, Henri Wahl <notifications@github.com> wrote:

> This sounds great - but I had that trouble again, so as a last resort I
> hope the 20160513 will fix this, pumping even more dirty workarounds into
> it :-(
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/HenriWahl/Nagstamon/issues/222#issuecomment-218816367>
>


-- 
*Eduardo D. Bergavera, Jr.*
Linux Admin
Email: edbergavera@gmail.com
OpenID: https://launchpad.net/~edbergavera
Github: https://github.com/edbergavera

**Comment by edbergavera** [comment] 2016-05-13 05:57
Hi,

No vanishing of statusbar encountered today. I will continue testing
tomorrow.

On Friday, 13 May 2016, Eduardo Bergavera <edbergavera@gmail.com> wrote:

> Testing  20160513 today.
>
> On Friday, 13 May 2016, Henri Wahl <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> This sounds great - but I had that trouble again, so as a last resort I
>> hope the 20160513 will fix this, pumping even more dirty workarounds into
>> it :-(
>>
>> —
>> You are receiving this because you commented.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/HenriWahl/Nagstamon/issues/222#issuecomment-218816367>
>>
>
>
> --
> *Eduardo D. Bergavera, Jr.*
> Linux Admin
> Email: edbergavera@gmail.com
> <javascript:_e(%7B%7D,'cvml','edbergavera@gmail.com');>
> OpenID: https://launchpad.net/~edbergavera
> Github: https://github.com/edbergavera
>
>

-- 
*Eduardo D. Bergavera, Jr.*
Linux Admin
Email: edbergavera@gmail.com
OpenID: https://launchpad.net/~edbergavera
Github: https://github.com/edbergavera

**Comment by edbergavera** [comment] 2016-05-15 13:20
No issue today

On Friday, 13 May 2016, Eduardo Bergavera <edbergavera@gmail.com> wrote:

> Hi,
>
> No vanishing of statusbar encountered today. I will continue testing
> tomorrow.
>
> On Friday, 13 May 2016, Eduardo Bergavera <edbergavera@gmail.com
> <javascript:_e(%7B%7D,'cvml','edbergavera@gmail.com');>> wrote:
>
>> Testing  20160513 today.
>>
>> On Friday, 13 May 2016, Henri Wahl <notifications@github.com> wrote:
>>
>>> This sounds great - but I had that trouble again, so as a last resort I
>>> hope the 20160513 will fix this, pumping even more dirty workarounds into
>>> it :-(
>>>
>>> —
>>> You are receiving this because you commented.
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/HenriWahl/Nagstamon/issues/222#issuecomment-218816367>
>>>
>>
>>
>> --
>> *Eduardo D. Bergavera, Jr.*
>> Linux Admin
>> Email: edbergavera@gmail.com
>> OpenID: https://launchpad.net/~edbergavera
>> Github: https://github.com/edbergavera
>>
>>
>
> --
> *Eduardo D. Bergavera, Jr.*
> Linux Admin
> Email: edbergavera@gmail.com
> <javascript:_e(%7B%7D,'cvml','edbergavera@gmail.com');>
> OpenID: https://launchpad.net/~edbergavera
> Github: https://github.com/edbergavera
>
>

-- 
*Eduardo D. Bergavera, Jr.*
Linux Admin
Email: edbergavera@gmail.com
OpenID: https://launchpad.net/~edbergavera
Github: https://github.com/edbergavera

**Comment by HenriWahl** [comment] 2016-05-18 09:45
@edbergavera @alekksi Hi there - any good news about non-vanishing-statusbars?

**Comment by alekksi** [comment] 2016-05-18 09:49
Hi,

Version 2.0-beta-20160513, no issues so far after nearly a week.
Cheers!

**Comment by edbergavera** [comment] 2016-05-18 10:10
Same with me here. No issues on vanishing statusbar. What I mean is it
doesn't fall behind other windows. I'm using the latest beta.

On Wednesday, 18 May 2016, alekksi <notifications@github.com> wrote:

> Hi,
>
> Version 2.0-beta-20160513, no issues so far after nearly a week.
> Cheers!
> On 18 May 2016 10:45, "Henri Wahl" <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
> > @edbergavera <https://github.com/edbergavera> @alekksi
> > <https://github.com/alekksi> Hi there - any good news about
> > non-vanishing-statusbars?
> >
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/HenriWahl/Nagstamon/issues/222#issuecomment-219977286>
> >
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/HenriWahl/Nagstamon/issues/222#issuecomment-219978555>
>


-- 
*Eduardo D. Bergavera, Jr.*
Linux Admin
Email: edbergavera@gmail.com
OpenID: https://launchpad.net/~edbergavera
Github: https://github.com/edbergavera

**Comment by HenriWahl** [comment] 2016-05-18 10:15
Sounds very very great. I almost dare to think about closing this issue....

**Comment by lorrainezo** [comment] 2016-05-20 12:17
Hello,

I have encounter this problem with version 20160519 64bit on Win8.1 64bit only at the FIRST start of application (folder .nagstamon don't exist) : you define a new server => error/warning are displayed. 
When you switch focus on a fullscreen window, icone "N" go in back of this window

After you exit Nagstamon and launch it for seconde time : no problem of focus

**Comment by edbergavera** [comment] 2016-05-20 13:36
No issue today for latest beta version on win7.

On Friday, 20 May 2016, lorrainezo <notifications@github.com> wrote:

> Hello,
>
> I have encounter this problem with version 20160519 64bit on Win8.1 64bit
> only at the FIRST start of application (folder .nagstamon don't exist) :
> you define a new server => error/warning are displayed.
> When you switch focus on a fullscreen window, icone "N" go in back of this
> window
>
> After you exit Nagstamon and launch it for seconde time : no problem of
> focus
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/HenriWahl/Nagstamon/issues/222#issuecomment-220590553>
>


-- 
*Eduardo D. Bergavera, Jr.*
Linux Admin
Email: edbergavera@gmail.com
OpenID: https://launchpad.net/~edbergavera
Github: https://github.com/edbergavera

**Comment by edbergavera** [comment] 2016-05-21 09:52
Update:

No issue today for latest beta version on win7.

On Fri, May 20, 2016 at 9:36 PM, Eduardo Bergavera <edbergavera@gmail.com>
wrote:

> No issue today for latest beta version on win7.
>
>
> On Friday, 20 May 2016, lorrainezo <notifications@github.com> wrote:
>
>> Hello,
>>
>> I have encounter this problem with version 20160519 64bit on Win8.1 64bit
>> only at the FIRST start of application (folder .nagstamon don't exist) :
>> you define a new server => error/warning are displayed.
>> When you switch focus on a fullscreen window, icone "N" go in back of
>> this window
>>
>> After you exit Nagstamon and launch it for seconde time : no problem of
>> focus
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/HenriWahl/Nagstamon/issues/222#issuecomment-220590553>
>>
>
>
> --
> *Eduardo D. Bergavera, Jr.*
> Linux Admin
> Email: edbergavera@gmail.com
> OpenID: https://launchpad.net/~edbergavera
> Github: https://github.com/edbergavera
>
>


-- 
*Eduardo D. Bergavera, Jr.*
Linux Admin
Email: edbergavera@gmail.com
OpenID: https://launchpad.net/~edbergavera
Github: https://github.com/edbergavera

**Comment by HenriWahl** [comment] 2016-05-22 13:37
@lorrainezo I tried to reproduce with a fullscreen Firefox but got no luck - Nagstamon always stayed on top. Which fullscreen application did you use? Can you always reproduce this?

**Comment by HenriWahl** [comment] 2016-05-29 12:15
How did it behave in the last days? I had no further problems regarding this issue. Might I close safely close it?

**Comment by edbergavera** [comment] 2016-05-29 12:41
Hi,

Tested latest beta today. No issues encountered.

On Sun, May 29, 2016 at 8:15 PM, Henri Wahl <notifications@github.com>
wrote:

> How did it behave in the last days? I had no further problems regarding
> this issue. Might I close safely close it?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/HenriWahl/Nagstamon/issues/222#issuecomment-222357505>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABhWeTvoVvt52Ew5E2KnuJf1Le3x2qJ5ks5qGYNNgaJpZM4IHHyX>
> .
>



-- 
*Eduardo D. Bergavera, Jr.*
Linux Admin
Email: edbergavera@gmail.com
OpenID: https://launchpad.net/~edbergavera
Github: https://github.com/edbergavera

**Comment by HenriWahl** [comment] 2016-05-29 17:51
Let's hope it is mostly fixed now.

**Closed by HenriWahl** 2016-05-29 17:51 UTC
