### ISSUE TITLE
Acknowledged filter not working

### ISSUE THREAD

**Issue by naiz0** [HenriWahl/Nagstamon#372] opened 2017-03-28 07:53 UTC
when i acknowledge a service which is down, the option "filter out acknownledges services and host" will not work. i still see the critical service although it is marked as acknowledged.

version: 2.1-20170323
OS: Linux Antergos 4.10.5-1

**Comment by BenoitPoulet** [comment] 2017-03-28 09:16
On which server type ?

**Comment by naiz0** [comment] 2017-03-28 09:30
oh, sorry
its IcingaWeb2

**Comment by Kharag** [comment] 2017-04-03 10:41
Confirmed using Nagstamon v2.1-20170323, Antergos Linux 4.10.6-1-ARCH

Using IcingaWeb2, Nagstamon still displays the service as critical even though it is marked as Acknowledged (there is even a check mark).

**Comment by Kharag** [comment] 2017-04-18 09:15
Any update? This is getting VERY annoying...

**Comment by HenriWahl** [comment] 2017-04-18 09:28
Do this non-filtered items have any other property, not only being acknowledged?

**Comment by Kharag** [comment] 2017-04-18 09:39
![nagstamon_services](https://cloud.githubusercontent.com/assets/2721885/25124329/ab875346-242b-11e7-8405-a28903bd91d3.png)

It looks like this. Can I provide you with any other information?

**Comment by HenriWahl** [comment] 2017-04-18 10:13
Hm... apparently noting special.
Which version of IcingaWeb2 do you use? Can you enable debugging to get some output? Even get the output your IcingaWeb2 monitor hands over to Nagstamon?

**Comment by Kharag** [comment] 2017-04-18 11:06
IcingaWeb2 is running on Centos 6 latest, Version 2.4.1 
I'll get you debug-output as soon as I'm able to.

**Comment by Kharag** [comment] 2017-04-21 08:11
Debug shows nothing...
Here is a sample icingaweb sends to Nagstamon (sorry, format is atrocious):
`{"attempt":1.0,"reachable":true,"state":0.0,"state_type":1.0}},"last_hard_state":0.0,"last_hard_state_change":1492629330.1123371124,"last_reachable":true,"last_state":0.0,"last_state_change":1492629330.1123371124,"last_state_critical":1492629270.0962951183,"last_state_ok":1492761930.1040179729,"last_state_type":1.0,"last_state_unknown":1492477557.6089699268,"last_state_unreachable":1492478035.2677481174,"last_state_warning":1492629300.1010930538,"max_check_attempts":5.0,"name":"Load","next_check":1492762110.0500001907,"notes":"","notes_url":"","original_attributes":null,"package":"_etc","paused":false,"retry_interval":30.0,"state":0.0,"state_type":1.0,"templates":["Load","nrpe-load","generic-service"],"type":"Service","vars":{"check":"check_load","host":"$address$","notification_interval":43200.0,"notification_type":"mail","timeout":"60"},"version":0.0,"volatile":false,"zone":""},"joins":{},"meta":{},"name":"allinred!Load","type":"Service"},{"attrs":{"__name":"allinred!Zombie processes","acknowledgement":0.0,"acknowledgement_expiry":0.0,"action_url":"","active":true,"check_attempt":1.0,"check_command":"nrpe-check-1arg","check_interval":180.0,"check_period":"","check_timeout":null,"command_endpoint":"","display_name":"Zombie processes","downtime_depth":0.0,"enable_active_checks":true,"enable_event_handler":true,"enable_flapping":true,"enable_notifications":true,"enable_passive_checks":true,"enable_perfdata":true,"event_command":"","flapping":false,"flapping_last_change":1492762015.1013829708,"flapping_negative":2874.0,"flapping_positive":0.0,"flapping_threshold":30.0,"force_next_check":false,"force_next_notification":false,"groups":[],"ha_mode":0.0,"host_name":"allinred","icon_image":"","icon_image_alt":"","last_check":1492762015.1013169289,"last_check_result":{"active":true,"check_source":"icinga.aic.at","command":["/usr/local/libexec/check_nrpe","-H","172.17.21.246","-c","check_zombie_procs","-t","60"],"execution_end":1492762015.100810051,"execution_start":1492762015.0106139183,"exit_status":0.0,"output":"PROCS OK: 0 processes with STATE = Z ","performance_data":["procs=0;5;10;0;"],"schedule_end":1492762015.1013169289,"schedule_start":1492762015.0099999905,"state":0.0,"type":"CheckResult","vars_after":{"attempt":1.0,"reachable":true,"state":0.0,"state_type":1.0},"vars_before":`

**Comment by HenriWahl** [comment] 2017-07-21 12:54
Related to #399

**Closed by HenriWahl** 2017-07-21 12:54 UTC
